# Generated by Django 3.1.6 on 2021-04-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('NO OPTION', 'NO OPTION'), ('HOURS', 'HOURS'), ('DIMENSIONS', 'DIMENSIONS'), ('TYPE', 'TYPE'), ('EXTRA', 'EXTRA'), ('ONTOULE', 'ONTOULE')], default=('NO OPTION', 'NO OPTION'), max_length=255)),
                ('price', models.FloatField(default=0)),
                ('extra_price', models.FloatField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('extra_price', models.FloatField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('details', models.ManyToManyField(blank=True, help_text='choose all Details affecting the parameter', related_name='parameters', to='backend.Detail')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='What is the name of the client?', max_length=100)),
                ('description', models.CharField(help_text='put a description for this offer', max_length=500)),
                ('number', models.IntegerField(help_text='How many pieces does the customer want', null=True)),
                ('extra_price', models.FloatField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('parameters', models.ManyToManyField(blank=True, help_text='choose all parameters affecting the offer (with ctr click you can choose more than one)', related_name='offers', to='backend.Parameter')),
            ],
        ),
    ]
