# Generated by Django 3.1.3 on 2021-02-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.CharField(help_text='put a description for this offer', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='extra_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
