# Generated by Django 3.1.6 on 2021-02-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='customer_name',
            field=models.CharField(help_text='What is the name of the client?', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='extra_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='offer',
            name='number',
            field=models.IntegerField(help_text='How many pieces does the customer want', null=True),
        ),
    ]
