# Generated by Django 3.1.6 on 2021-02-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210214_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='extra_price',
            field=models.FloatField(default=0),
        ),
        migrations.RemoveField(
            model_name='detail',
            name='parameter',
        ),
        migrations.AddField(
            model_name='detail',
            name='parameter',
            field=models.ManyToManyField(to='backend.Parameter'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='extra_price',
            field=models.FloatField(default=0),
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='offer',
        ),
        migrations.AddField(
            model_name='parameter',
            name='offer',
            field=models.ManyToManyField(to='backend.Offer'),
        ),
    ]
