# Generated by Django 3.1.6 on 2021-02-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210214_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='category',
            field=models.CharField(choices=[('HOURS', 'HOURS'), ('DIMENSIONS', 'DIMENSIONS'), ('TYPE', 'TYPE'), ('EXTRA', 'EXTRA')], default=('HOURS', 'HOURS'), max_length=255),
        ),
    ]
