# Generated by Django 3.1.6 on 2021-03-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210228_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='parameter',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
