# Generated by Django 3.1.6 on 2021-03-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210228_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='category',
            field=models.CharField(choices=[('NO OPTION', 'NO OPTION'), ('HOURS', 'HOURS'), ('DIMENSIONS', 'DIMENSIONS'), ('TYPE', 'TYPE'), ('EXTRA', 'EXTRA'), ('ONTOULE', 'ONTOULE')], default=('NO OPTION', 'NO OPTION'), max_length=255),
        ),
        migrations.AlterField(
            model_name='detail',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
