# Generated by Django 3.1.6 on 2021-03-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210311_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
