# Generated by Django 3.1.6 on 2021-03-24 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210317_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
