# Generated by Django 3.1.6 on 2021-03-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210324_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='customer_name',
            field=models.CharField(default='noCustomerName', help_text='What is the name of the client?', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.CharField(default='noDescription', help_text='put a description for this offer', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parameter',
            name='description',
            field=models.CharField(default='noDescription', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(default='noName', max_length=100),
            preserve_default=False,
        ),
    ]
