# Generated by Django 3.1.6 on 2021-03-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20210324_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='parameters',
            field=models.ManyToManyField(blank=True, help_text='choose all parameters affecting the offer', related_name='offers', to='backend.Parameter'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='details',
            field=models.ManyToManyField(blank=True, help_text='choose all Details affecting the parameter', related_name='parameters', to='backend.Detail'),
        ),
    ]
